# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec14a704563ae0ab06859a891b86629b31fa2e5ef92cceebdbb53de73da7591ccf3f024a18f14ddcc0b285d4a5e1ef3b6f1704b89b4513c9388a404413e74240

test:
  secret_key_base: f4032b1224d5443cd8d0ae9ecf4a45c1d713cbadcc6e13edbdeefd01bad820b75606d7733c78ca542e3178112941d9bb0b889ab86d83bf0f253cb94ef8f88af9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
