# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52525ac5ebab3c62c8384e6efc12c2f9e8be9de85c854b814a26b456cd4a8576d090ae87116eec95db0b31e69f5b9d6f393a88008d2c85dbd257c9ab9b69d92b

test:
  secret_key_base: 7e4c7bcd53e9cee2d127abd79297e228587a6772ace9c7b930d8873a6b5f884c2a8d5995a1171d380b62d7d2680423d619c312eff04e350f21015dfe3ed2db1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
